livepeer/lpms

- segmenter/video_segmenter.go
- segmenter/video_segmenter_test.go
- stream/hls.go
- stream/stream.go
- stream/stream_subscriber.go
- stream/stream_subscriber_test.go
- stream/stream_test.go
- vidlistener/listener.go
- vidplayer/player.go
- vidplayer/player_test.go
Most of this PR is the StreamSubscriber, which allows a subscription workflow for any VideoStream, so a stream can be broadcasted to multiple subscribers.
> Video segment

- cmd/rtmp_segment_packer/main.go
- cmd/runner/main.go
- segmenter/video_segmenter_test.go
- stream/file_stream.go
- stream/hls.go
- stream/hls_test.go
- stream/stream.go
- stream/stream_subscriber.go
- stream/stream_subscriber_test.go
- stream/stream_test.go
- vidplayer/player.go
- vidplayer/player_test.go
This change is related to how HLS is treated in LPMS.
* We add a buffer cap limit, so it doesn't just keep adding HLS segments
* HLSBuffers can now generate playlists from its segments
* Add methods to synchronously read HLS from a VideoStream
> HLS changes

- cmd/rtmp_segment_packer/main.go
- cmd/runner/main.go
- segmenter/video_segmenter.go
- segmenter/video_segmenter_test.go
- stream/file_stream.go
- stream/hls.go
- stream/hls_test.go
- stream/stream.go
- stream/stream_subscriber.go
- stream/stream_subscriber_test.go
- stream/stream_test.go
- transcoder/external.go
- transcoder/external_test.go
- vidlistener/listener.go
- vidplayer/player.go
- vidplayer/player_test.go
now load HLS segment number and duration, and maintain the playlist in the HLS buffer as the segments are written instead of generating a new playlist for every request
We change the segmenter implementation to directly load the time information instead of waiting for the playlist thread (which is not guaranteed to be running).  We also simplified HLSBuffer by removing the playlist write, since the node is are now directly maintaining its own playlist instead loading it from the source.
> HLS SegNo and Duration

- cmd/rtmp_segment_packer/main.go
- cmd/runner/main.go
- lpms.go
- segmenter/video_segmenter.go
- segmenter/video_segmenter_test.go
- stream/stream_subscriber.go
- vidlistener/listener.go
- vidlistener/listener_test.go
- vidplayer/player.go
Make mobile publishing work.  Changes:
* Make sure we always set the same headers - that way the CDN will invalidate quickly and always look for new content, even with the URL is the same.
* Clean up files for the segmenter - had to do this because we are now streaming to the same ID over and over.
* Add VOD path
* Did a test with master playlist, but not useful for now.  Let's leave it in - maybe it'll be useful when we do adaptive bitrate streaming.
> Video player fix

- circle.yml
- stream/basic_hls_videostream.go
- stream/basic_hls_videostream_test.go
- transcoder/ffmpeg_segment_transcoder.go
- We make a change to the HLS stream to keep a buffer of at least 3 segments.  Until then, the video will not be available.  This increases the video delay to about 30 seconds, but improves the playback stability.
- We also remove the waiting pattern in GetHLSSegment, so the user of the library is not forced to wait.
- We add a flag to the ffmpeg transcode command to keep the timing information.
> stability improvement

- ffmpeg/lpms_ffmpeg.c
- transcoder/ffmpeg_segment_transcoder.go
- transcoder/ffmpeg_segment_transcoder_test.go
Fixes a segfault.
Also a small API cleanup.
> transcoder: Fix double free on invalid output.

- ffmpeg/lpms_ffmpeg.c
- transcoder/ffmpeg_segment_transcoder_test.go
- vidlistener/listener.go
- vidlistener/listener_test.go
transcoder: Set return code when opening output file.  …
Fixes a crash. Let that be a lesson to follow through on TODOs
within the code; a test would have caught the issue instantly.
listener: Disconnect publisher if gotStream returns error.
Note that ^ is a semantic change to the API. Made to accommodate https://github.com/livepeer/go-livepeer/pull/380 , but I think the behavior still makes sense on its own.
> Fix crash and disconnect listener on `gotStream` error

- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
Crashed if the file was invalid or nonexistent.
> ffmpeg: Fix crash in length check.

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
- transcoder/ffmpeg_segment_transcoder_test.go
* d9e09b21a4fd8d2a1a6c858e708a512c4540038a - segmenter: FIx a crash and verify output stream ordering
* 54f87083a40654c78928bea748e40c72a1b57476 - transcoder: Fix rounding with odd-valued rescaled resolutions.
* f1d09dcf30bba01151b33298d91f211f8d21c126 - medialen: Remove media stats checker.
* 8fc5c435b8403325c7f795bb143694b14ff76775 - segmenter: Delete segments as they fall off the playlist.
* c2df2d703e0c627a4b21670087f448a7f24f2f1d - ffmpeg: Incorporate a test helper to reduce boilerplate.
* 63bcda9b3a1f3cb624028aa50fcb951a638bced5 - transcoder: Fix buzzing in resampled audio output.
> Misc fixes to LPMS

- vidplayer/player.go
- vidplayer/player_test.go
Right now if `getSegment` returns `ErrNotFound` error player return HTTP status coded 500, which is misleading. PR fixes that.
>  In case segment was not found, return 404 instead of 500

- vidplayer/player.go
See title.
FWIW I didn't test LPMS itself — I tested this by building it into go-livepeer and looking at output from there. Seems pretty straightforward, though.
```
▶ curl -i --head https://bbb.stream.town/stream/499d46af/P360p30fps16x9/288.ts
HTTP/2 200
server: nginx/1.14.2
date: Thu, 07 Mar 2019 23:09:07 GMT
content-length: 230300
access-control-allow-origin: *
access-control-expose-headers: Content-Length
cache-control: max-age=5
via: 1.1 google
alt-svc: clear
```
Fixes #108
> add content-length header to video segments

- ffmpeg/lpms_ffmpeg.c
This change allows ffmpeg to use as many threads as it can for
the encoding process. The renditions for each frame are still
processed sequentially, but each rendition can now use multiple
threads.
This does make it more difficult to characterize the overall behavior
or capacity of a node, but it is necessary to go fast for well-tuned
nodes.
Fixes https://github.com/livepeer/go-livepeer/issues/788
> ffmpeg: Remove one-thread-per-segment restriction.

- segmenter/video_segmenter_test.go
- stream/basic_rtmp_videostream.go
- stream/basic_rtmp_videostream_test.go
- vidlistener/listener_test.go
Fixes a number of issues identified by the golang race detector as brought up by @angyangie .
Ran unit tests via `go test -race` and the Livepeer goclient (although not with race).
Commits:
https://github.com/livepeer/lpms/commit/533c1cc3e091ca064b10a9d40b0e06cbba97c407 stream: Make RTMP stream tests threadsafe.
https://github.com/livepeer/lpms/commit/9c3a55568289da350e28fe0c346f552389b33857 stream: Make BasicRTMPVideoStream threadsafe.
https://github.com/livepeer/lpms/pull/118/commits/7740287b9a60a2952a4c2453882c28fd76ed3094 segmenter: Don't use default RTMP port for tests.
Hopefully it saves someone else from spending time debugging if
they forget there's a RTMP server also running on the machine.
https://github.com/livepeer/lpms/pull/118/commits/c371e7ad22863a5b0f072f6b69fc8d4f184ee717 …
> Make RTMP handling more thread safe

- README.md
- cmd/transcoding/transcoding.go
- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_errors.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
- ffmpeg/nvidia_test.go
- test.sh
This patch set introduces preliminary support for processing on nvidia GPUs. 
* Decode
* Encode
* Rescale
* Selectable GPUs
Various combinations are supported:
* Software-only processing
* Software decode, GPU rescale, GPU encode
* GPU decode, GPU rescale, software encode
* GPU-only processing
As much processing is kept on the GPU device as possible. Eg, if rescaling is required while only one of encode / decode is run on the GPU, then the rescaling will be done on the GPU. Only one GPU is used at a time for a given transcode.
A new API is introduced to support GPU : `Transcode2` . The old `Transcode` API has been internally retrofitted to use the new API with software-only processing, but to take advantage of GPUs, the new API will need to be used. …
> Preliminary nvidia support.

- cmd/example/main.go
- core/lpms.go
- segmenter/video_segmenter_test.go
- stream/basic_hls_videostream.go
- stream/basic_rtmp_videostream.go
- stream/basic_rtmp_videostream_test.go
- stream/interface.go
- vidlistener/listener.go
- vidlistener/listener_test.go
This allows us to pass around per-stream data from MakeStreamID
without storing it outside LPMS.
In support of https://github.com/livepeer/go-livepeer/issues/793
> vidlistener: Support opaque user data.

- cmd/example/main.go
```
cmd/example/main.go:182:14: Infof call has arguments but no formatting directives
```
> fix cmd/example/main.go: Infof call has arguments but no formatting directives

- core/lpms.go
- go.mod
- go.sum
- segmenter/video_segmenter.go
- segmenter/video_segmenter_test.go
- stream/basic_rtmp_videostream.go
- stream/basic_rtmp_videostream_test.go
- stream/interface.go
- vidlistener/listener.go
- vidlistener/listener_test.go
- vidplayer/player.go
- vidplayer/player_test.go
This PR sets us up for managing `go-livepeer` dependencies using `go mod`.
Users building standalone lpms using `GOPATH` will still have to manually run `go get github.com/livepeer/joy4@livepeer` - This PR should at least get them a step closer by pointing them to the correct repository.
Users building standalone lpms using `go mod` should be automatically pointed to the correct revision of joy4.
Users building `go-livepeer` must continue building using the vendored lpms and `GOPATH` until `go mod` is completely ready.
This does nothing to harm to current state of things for users with today's build methods.
> move to go mod and `livepeer/joy4@livepeer`

- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
https://github.com/livepeer/lpms/commit/4e8c118536ac7cd69de174dfa3f653e5ef4974f6 : ffmpeg: Drain queued frames from the filter and encoder.  …
This allows for better resource management.
Multiple frames may be output for a given filter call, such as
upsampling the frame rate. This led to running out of
surfaces in GPU-encoding mode, and steadily increasing memory usage
in software-encoding mode.
Likewise, GOP structure may result in the encoder having several frames ready
to be returned after being fed earlier frames with no immediate result.
The transcode loop is reworked to:
0. Decode a frame
1. Feed the filter graph with the decoded frame
1a. Feed and drain the encoder if no filter graph is configured
2. Drain the filter graph as much as possible
3. Feed and drain the encoder for each …
> Drain queued frames from the filter and encoder.

- segmenter/video_segmenter_test.go
This feels a bit like a band-aid  -- if it's failing before writing the headers, is it really disconnecting "mid-stream" ? --  but seems to make the tests pass for now.
Fixes https://github.com/livepeer/lpms/issues/137
Fixes https://github.com/livepeer/lpms/issues/136
> segmenter: Fix tests.

- cmd/transcoding/transcoding.go
- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
* Adds support for counting decoded pixels
* Allows passing in empty output parameters to force a decode-only flow.
The GetMediaInfo function in go-livepeer becomes:
```golang
func GetMediaInfo(fname string) (*MediaInfo, error) {
in := &TranscodeOptionsIn{Fname: fname}
res, err := Transcode3(in, nil)
if err != nil {
return nil, err
}
return &res.Decoded, nil
}
```
This could be further specialized to return pixels only, rather than a generic struct, because go-livepeer not likely to need the frame count.
Fixes https://github.com/livepeer/lpms/issues/125
> Count decoded pixels.

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
Still needs checking for memory leaks, but opening this for review to get feedback.
This patch set modifies the `TranscodeOptions` struct to take options for the video encoder, audio encoder and muxer.  These options take a common `ComponentOpts` struct which specifies a name, and a set of options that correspond directly to the FFmpeg AVOptions for the component. Using these AVOptions should allow us to remove hardcoded and ad-hoc configuration options.  See "Follow Ups" for more details.
On top of the ComponentOpts, special-case handling is added for stream copy and stream dropping.
This PR is backwards compatible with the existing Transcode3 API. If the audio/video options are omitted, the original behavior is preserved: x264 and AAC are encoded (or nvenc if hardware acceleration is …
> Add stream copy and dropping.

- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
ffmpeg: Fix frame dropping in filtergraph at EOF.
This is done by setting the EOF timestamp of the filtergraph
such that the timestamp is *after* the last frame inserted.
Also add tests exhibiting various cases uncovered in the process
of fixing this.
Fixes https://github.com/livepeer/lpms/issues/154
> Fix frame dropping in filtergraph at EOF

- .circleci/config.yml
- ffmpeg/ffmpeg_test.go
- ffmpeg/nvidia_test.go
- go.mod
- go.sum
- install_ffmpeg.sh
- segmenter/video_segmenter_test.go
- transcoder/ffmpeg_segment_transcoder_test.go
Splitting up some of https://github.com/livepeer/lpms/pull/141 into this PR in order to make the changes a touch less overwhelming.
* Updates FFmpeg to use the Livepeer forked branch at https://github.com/livepeer/ffmpeg
* Updates joy4 to fix some breakage resulting from the ffmpeg update. Specifically, this [change](http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=ce1fcc8cede2971f6e36119e9dd41fb41b36c63a) modified the general libav code to *not* treat general IO errors as EOF. This broke some tests with the segmenter. Drilling down on the problem revealed that ffmpeg has a stricter view of what constitutes a proper EOF for RTMP : the playback stream needs to be torn down completely. Turns out that joy4 was simply terminating the connection, rather than tearing down the stream …
> Update joy4 and ffmpeg.

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
- https://github.com/livepeer/lpms/commit/a92aab19541fc2a06c1c6aa3a4c6cca398a425a6 : ffmpeg: Support frame rate passthrough.
- https://github.com/livepeer/lpms/commit/b20b031c36402da7863f52957067bbcf3bed8a7e : segmenter: Loosen up options used with nc.
Makes things a bit more portable.
Fixes https://github.com/livepeer/go-livepeer/issues/1239
> ffmpeg: Pass through FPS.

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_errors.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
- ffmpeg/nvidia_test.go
- install_ffmpeg.sh
- transcoder/ffmpeg_segment_transcoder_test.go
The commits in this PR are rebased and squashed from the following WIP branch: https://github.com/livepeer/lpms/compare/ja/old-bottleneck
There is a substantial overhead cost to starting new transcode sessions on a GPU. Adding more streams and GPUs [exacerbates](https://gist.github.com/j0sh/ae9e5a97e794e364a6dfe513fa2591c2) the problem [1].  Up until now, a new GPU session has been started for each segment that's received. This has led to a massive slowdown in transcoding latency, and becomes worse with each additional concurrent stream.
To mitigate this setup overhead, we make transcode sessions persistent for each stream, so segments after the first can re-use the same session.
[1] There may be a global lock somewhere within FFmpeg or the Nvidia drivers, or it may be intrinsic. …
> LPMS bottleneck fix

- ffmpeg/ffmpeg_test.go
B-Frames are not dropped during stream copy. Test Case validates the concern raised in #164
> Validate whether stream copy skips B-Frames as mentioned in Issue#164

- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
Fixes Issue #166. 
test case already available in nvidia_test.go
> ffmpeg: return lpms_ERR_INPUT_PIXFMT for non 420p pixel formats

- README.md
- ffmpeg/api_test.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
https://github.com/livepeer/lpms/commit/248f7f490b112d302afa677a244f16b0f8b39c2a ffmpeg: Refactor a bit of output cleanup. …
Hopefully the intent of the renamed functions are clearer.
https://github.com/livepeer/lpms/commit/ad4848e2755d2e9623209f59c92b8b95ac518164 ffmpeg: Apply latest gofmt to tests.
55f2672 ffmpeg: Remove unneeded function preamble. …
The preamble is applied automatically now.
1532688 ffmpeg: Fix typo in test logging.
https://github.com/livepeer/lpms/commit/3f516780740f977b5ef7665dd0fa273f363ad80c README: Add audio to example command line. (supersedes https://github.com/livepeer/lpms/pull/175 )
> Miscellaneous fixes.

- vidplayer/player.go
- vidplayer/player_test.go
Whenever I get the sense that something smells wrong, it usually ends up being correct.
The old behavior ended up being unnecessarily restrictive.
In particular, go-livepeer now stores `.tempfile` extensions
for local temporary storage, and that hits this code path. No reason
why it shouldn't work.
https://github.com/livepeer/go-livepeer/blob/4ba2a732a31b673254008faeb903e28bf7039a74/core/orchestrator.go#L499-L506
> vidplayer: Allow any file extension through.

- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
Seems to have worked, although it's not yet clear whether the
full color range is properly processed within the GPU, or if
there is some truncation happening. In any case, the resulting
quality looks Close Enough.
> ffmpeg: Allow decoding of yuvj420p.

- ffmpeg/ffmpeg_errors.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
- ffmpeg/nvidia_test.go
Resolves #185
Tested manually with the mpegts file in #185 - it now throws the correct error. (Still segfaults later though):
```$ ./transcoding segment.ts P240p25fps16x9 nv 0
Setting fname segment.ts encoding 1 renditions with nv
[mpegvideo @ 0x42b5480] Format mpegvideo detected only with low score of 12, misdetection possible!
Non H264 codec detected in input
Unable to open video decoder
Freeing input based on OPEN INPUT error
ERROR: logging before flag.Parse: E0414 18:54:09.197087  119394 ffmpeg.go:318] Transcoder Return : <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5cdcae]
goroutine 1 [running]:
main.main()
/home/darkapex/go/src/github.com/livepeer/lpms/cmd/transcoding/transcoding.go:78 …
```
> ffmpeg: Exit early for non-H264 input w/ NVDEC

- ffmpeg/api_test.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
* Maintain diff of sent packets/recv frames to know when decoder is done flushing.
* Stop sending sentinel packets after n=5 attempts of not getting any valid frame back.
* Fix fps filter dropping 1-frame segments by sending a flush frame with a longer pts.
* Add parameterized unit tests to reproduce #168 
In #187 I tried to fix the short segment flushing using NULL packets, but it had heavy performance impact. So I've created this fresh PR because that got very messy.
I tried my best to benchmark this against master and it seems to perform equally well. I noob though, pls verify :)
> ffmpeg: Fix short segments flushing without using NULL packets

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/nvidia_test.go
- ffmpeg/videoprofile.go
**Why?**
These changes are for supporting non-integer FPS output in LPMS. See [go-livepeer#1474](https://github.com/livepeer/go-livepeer/issues/1474) for details.
**What?**
* Add a `FramerateDen` field in VideoProfile
* Set the rational FPS in the FFmpeg filtergraph string & Cgo transcoder params
* Add unit tests to verify that common fractional FPS cases work as expected
> Support non-integer framerates

- ffmpeg/api_test.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
Fixes a number of issues around handling consecutive MP4 segments.
Closes https://github.com/livepeer/go-livepeer/issues/1514
ffmpeg: Fix decoding consecutive MP4s. … 9e0d589
A new demuxer has to be initialized for each non-mpegts input.
Preserving the old behavior saves 1% of performance.
ffmpeg: Short-circuit flushing + demuxer reset. … 8746b09
No longer have to force a read until EOF if exiting early.
Does not change anything, but it's a better way of doing things.
ffmpeg: Apply muxer options to consecutive segments with GPU transcoding … 16f55a1
For VideoProfile-directed mp4 outputs, this resulted in trailing moov.
> Fix processing of consecutive MP4 segments

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/nvidia_test.go
- ffmpeg/videoprofile.go
Refer to the parent issue in go-livepeer: https://github.com/livepeer/go-livepeer/issues/1531
* Add a new enum for Encoder profiles
* Add a field in VideoProfile struct to hold the encoder (h264) profile
* Pass the relevant AVOptions to FFmpeg to enable the profile
* Support *Constrained High* by disabling B-frames using `-bf 0`
* Manually tested all profiles work as expected
* Manually tested by default no extra AVOption is passed so that encoder uses default profile (nvidia default is `main`, x264 default is `high`)
* Added unit tests for all the profiles, including B-frames verification for Baseline & Constrained High
> ffmpeg: Add support for H264 profiles

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
- ffmpeg/nvidia_test.go
- ffmpeg/videoprofile.go
- test.sh
Adds user control over the output GOP interval.
* Add a "GOP" field to VideoProfile in units of `time.Duration`.  8f0ad3555d9f1f385e4d17180e6cd6c0a780383d
* If fixed FPS output is used, use built-in `g` AVOption to have the encoder output keyframes based on a fixed frame interval. 8f0ad3555d9f1f385e4d17180e6cd6c0a780383d
* If passthrough FPS is used, keep track of when the next keyframe is due based on timestamps and explicitly assign frames to keyframes within LPMS. 78548c9079617ff8c6cddb4a90cb2fafe5ddf9da
* Adds an intra mode to demonstrate support for extended GOP modes. f1ca834f064f6b052fc9a48bde72aedf3024478f  
* simplify test runner 4c6d62c9f22011e48a538c46a885397b1fde475d
* Error checking for invalid GOP values. This starts at -1 and is bumped down to -2 for intra mode. This should …
> ffmpeg: Knob to tune output GOP intervals.

- ffmpeg/api_test.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/nvidia_test.go
**Why?**
Look at #199 for details on what this PR fixes.
**What has been changed?**
* Disable check for Out-Of-Order segments
* Set uniformly-increasing monotonic PTS as the input to filtergraph (when FPS filter is used)
* Set `opaque` to original PTS
* Use original PTS rescaled to the filtergraph output-timebase to calculate the correct output PTS
* This is done only for the first frame of the segment
* Store the difference between the output PTS filtergraph sent for the first frame, and the calculated PTS for the first frame of the segment
* Apply this difference on every subsequent frame (This ensures uniformly increasing output for a particular segment, but maintains the original intra-segment order)
For example see the output of the AlternatingTimestamps test case …
> ffmpeg: Custom timestamp handling

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/lpms_ffmpeg.c
- ffmpeg/lpms_ffmpeg.h
- ffmpeg/nvidia_test.go
**Why?**
For details check the audio-only bug this PR fixes #203
**How?**
We bypass the usual transcoding process for the first n-segments of a stream that do not have any frames, but do have a valid *video substream* present in the container format.
The bypassing is done by forcing the copy transcoder https://github.com/livepeer/lpms/commit/8bc28e3f702049a17c24ab2041857a47d8af51bf for such segments.
**Testing Done:**
- Manually reproduced with a failing segment from prod
- Reproduced the issue with a unit test https://github.com/livepeer/lpms/commit/c372f562194ea0c88595d7f05797f827f6ffd683
- Fixed & verified the fix for both of the above ^
> Handle zero-frame (audio-only) segments at the start of a session

- ffmpeg/ffmpeg.go
**Why?**
Refer to https://github.com/livepeer/go-livepeer/pull/1608 for details on why this was needed.
**What?**
Ensure the bypass implemented for audio-only segments at the start of a stream only happen for MPEG-TS muxer format and help out the transcoder by passing the out format through `VideoProfile.Format`. (go-livepeer uses `.tempfile` extension because the segs might be .ts or .m4s)
**Note:** This is a temporary hack, and I want to further emphasize that the transcoder should support a Go function (that calls Cgo ffmpeg api) to *only check* whether a bypass is needed. The actual bypass logic (and what options to tweak) should be maintained upstream either in the Broadcaster code (if needed for public network) or the API product code.
> ffmpeg: bypass txcoder only for mpegts

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
**What is done?**
* Reverted the bypassing performed for initial segments with broken video streams.
* Retained the detection code and now throw an early error for such streams to prevent the extra-cost associated with initializing contexts for decoding.
**Why?**
The original error is not reproducible anymore, and the current state of `master` which bypasses segments altogether may cause issues with playback and is not a stable well-tested solution.
> ffmpeg: Throw error instead of bypassing for audio-only stream

- ffmpeg/ffmpeg.go
Fix a newbie Cgo error of not freeing `C.CString` that golang's GC doesn't know about.
> ffmpeg: Fix cstring memleak

- ffmpeg/decoder.c
- ffmpeg/encoder.c
- ffmpeg/ffmpeg.go
- ffmpeg/filter.c
- ffmpeg/logging.h
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
**Why**
Clean up logging in the Cgo code (Fixes #209)
**What**
- Use ffmpeg's logging library with appropriate levels like ERROR, WARNING, INFO instead of throwing everything on stderr blindly.
- Add a well defined log prefix like `[lpms.decoder.xyz]` of the component from where the log is being emitted.
- Does *not* add any extra INFO logs, will do it separately the next time I go around debugging something and need to trace out the location in the transcoder pipeline
**Notes**
Commit(s) to be applied on top of #212
> ffmpeg: Improve Cgo logging

- .circleci/config.yml
Use go1.15.5 in CI. Mainly makes sure tests pass with this go version.
Fixes #215
> ci: Use go1.15.5

- ffmpeg/api_test.go
- ffmpeg/decoder.c
- ffmpeg/ffmpeg_errors.go
- ffmpeg/nvidia_test.go
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
**Why?**
The video decoder currently gets stuck in an infinite loop while flushing if the input segment does not contain any keyframes, as it uses the first keyframe packet to flush the decoder buffer.
**What?**
If no keyframe packet is found after reading and sending all packets to the decoder, return an explicit error and don't try to flush.
**Testing**
**Fixes**
Fixes #219
> decoder: Error out on segments with no keyframe packets

- ffmpeg/decoder.c
**What?**
Fix the incrementing logic of the flush "sentinel" packet counter. Previously that counter was not updated if FFmpeg threw an error for the packet, which lead to an infinite loop.
**Why?**
Fixes #222
> decoder: update sentinel counter even for bad packets

- ffmpeg/ffmpeg_errors.go
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
- Export LPMS error strings to avoid re-definition in go-livepeer.
- Remove old unused "Out of order" segment error as we can handle those now.
This commit is needed for https://github.com/livepeer/go-livepeer/issues/1756
> ffmpeg: Export lpms errors

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_errors.go
**Why?**
Needed for https://github.com/livepeer/go-livepeer/issues/1774
**What?**
Add more errors, and separate out the "Non Retryable" category to be used by the B. Updated list of errors includes:
- All LPMS C-module errors
- A subset of LPMS Go-module errors around bad input/parameters
- A subset of [internal ffmpeg errors](https://ffmpeg.org/doxygen/trunk/error_8c_source.html#l00034) that may get surfaced back to the B
> ffmpeg: separate non-retryable errors

- README.md
`-tag` does not seem to be a valid flag for `go test`. I had to use `--tags=nvidia` in order to run the GPU tests.
> README: --tags instead of -tag for Nvidia tests

- ffmpeg/api_test.go
- ffmpeg/encoder.c
- ffmpeg/nvidia_test.go
- install_ffmpeg.sh
**Why?**
Needed for #232 
**What's changed?**
- Ensure that output's AVStream and AVCodec have the correct framerate value when using passthrough (i.e. octx->fps = 0) https://github.com/livepeer/lpms/pull/229/commits/3b5689d177504c0f47bba2c04e5d8780e9bb68e4
- Update ffmpeg to include a cherry-picked bugfix that ensures that NVENC respects the `AVCodec->framerate` value we've set. https://github.com/livepeer/FFmpeg/pull/2
**Testing**
- Unit test introduced in https://github.com/livepeer/lpms/pull/229/commits/700787e6d8ca1ba3b008180130033a9708dc08d5 fails before the changes in the PR, but passes after the changes in the PR
(manually tested on my GTX 1060 and livepeer's GTX 1070)
**Note To Reviewer**
- A manual `git checkout master && git rebase jai/streamfps && git merge` is preferred to …
> encoder: set output framerate correctly for passthrough

- .gitignore
- ffmpeg/decoder.c
- ffmpeg/decoder.h
- ffmpeg/encoder.c
- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_darwin.go
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
- ffmpeg/transmuxer_test.go
Adds special 'transmuxing' mode. In that mode output will be open on first transcode and closed in `lpms_transcode_stop`.
This allows to join multiple segments into one output.
Also adds `Transcoder.Discontinuity` which tells transmuxer that next segment is part of the new stream, and so timestamps of the next segment will be shifted to create one continuous stream.
> Add transmuxing to transcode pipeline

- cmd/scenedetection/scenedetection.go
- ffmpeg/api_test.go
- ffmpeg/detector.go
- ffmpeg/encoder.c
- ffmpeg/ffmpeg.go
- ffmpeg/filter.h
- ffmpeg/nvidia_test.go
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
- install_ffmpeg.sh
**Motivation**
Since the time the lpmsdemo fork was created, the LPMS codebase architecture has changed quite a bit. 
The ideal architecture is to implement with inference DNN filter, not integrating directly into LPMS C code.
So the source code was modified to reflect this idea.
Following figure shows the workflow.
**Build & Test**
-FFmpeg build
To use lvpdnn inference filter, clone from [here ](https://github.com/oscar-davids/FFmpeg/tree/dev-lpvdnn)and must be built with -enable-libtensorflow
-Test
making or getting a trained model, refer to [ModelPath](https://github.com/oscar-davids/lpms/blob/3ebb3493fb6b4a1111ac9d0e6cb3ebdeb204db3e/ffmpeg/videoprofile.go#L97)
software processing
go run cmd/transcoding/transcoding.go transcoder/test.ts **PDnnDetector**,P240p30fps16x9 sw
nvidia …
> Scene classification prototype

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
change signature of `HasZeroVideoFrame` and `HasZeroVideoFrameBytes`
to return boolean instead of integer
> Change signature of `HasZeroVideoFrame` and `HasZeroVideoFrameBytes`

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
**Why?**
Fixes #238 
By default our GPU encoder `nvenc` does not enable B-frames unless explictly set via the ffmpeg `-bf` flag - i.e currently the GOP of nvenc output looks like `IPPPPP...PPI` regardless of the selected encoding profile, because `-bf=0` by default for nvenc.
This is different from our CPU encoder `x264`, which has the corresponding internal flag [set to `3`](https://gist.github.com/newfront/875122#file-x264-encoding-options-L134 ) by default. This leads to GOPs with (at max) 3 B-frames between any two P-frames `I..PBBBP..I` if the user selected Main/High encoding profile.
We'd like the GPU encoded output to be similar to the CPU encoded one.
**What has changed?**
This patch explicitly sets the ffmpeg flag `-bf=3` for Main/High encoding profile - fixing those profiles' …
> ffmpeg: Enable B-frames with GPU encoding

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
ffmpeg doesn't close pipes, and when opening stream
doesn't read all the data - so `io.Copy` was waiting
forever.
> fix HasZeroVideoFrameBytes for long segments

- .circleci/config.yml
New debian release (bullseye) [broke our CI pipeline](https://app.circleci.com/pipelines/github/livepeer/lpms/202/workflows/e210044f-b441-4b05-9960-ef6403e35723/jobs/640), which is still using the previous debian release (buster).
One solution is to [edit the `apt-get update` command](https://stackoverflow.com/questions/68802802/repository-http-security-debian-org-debian-security-buster-updates-inrelease) in the original script. But turns out the latest golang v1.15 image by CircleCI `circleci/golang:1.15.15` is (presumably) already on bullseye, and works without tweaking the apt update process.
> ci: Fix breaking builds due to debian bullseye release

- ffmpeg/decoder.h
- ffmpeg/filter.h
I ran into 'undefined reference' error when trying to launch debugging from VS Code and GoLand. The reason is that `inline` specifier without `static` not always results in function inlining, and behavior is not consistent across C compilers and C standards. It can be reproduced like that:
````
CGO_CFLAGS="-std=gnu17" go build -gcflags=all="-N -l" cmd/scenedetection/scenedetection.go
````
It's hard to pinpoint exactly which C compiler settings plain `go build` uses, so I'm not sure why it works fine, probably because of C compiler and optimization flags combination. I added `static` specifier to all inline functions, which should produce intended compiler behavior.
> Use static inline instead of inline

- ffmpeg/decoder.h
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
- ffmpeg/transmuxer_test.go
We have case where source segment has two audio packets with the same timestamp. This isn't allowed and FFmpeg returns error in the process of transmuxing.
This PR skips such packets.
Fixes https://github.com/livepeer/internal-project-tracking/issues/171
> transmuxing: skip packets with same timestamp

- install_ffmpeg.sh
fixed mpeg7 cuda signature filter memory leak
> fixed mpeg7 cuda signature filter memory leak

- ffmpeg/ffmpeg.go
- install_ffmpeg.sh
Removes gnutls from list of dependencies.
Not need because we're [removing](https://github.com/livepeer/go-livepeer/commit/62d28bf6c59f58eba62fcec8f32fae9721edee30) http and https protocols from ffmpeg build.
> Do not link GnuTLS library

- .circleci/config.yml
- segmenter/video_segmenter_test.go
Turned out when test function pumps data to TCP connection too fast it leads to that connection being reset.
Add small delay to that test function to slow down data transfer and that fixed issue.
> fix segmenter test

- ffmpeg/api_test.go
- ffmpeg/decoder.h
- ffmpeg/nvidia_test.go
- ffmpeg/transcoder.c
- install_ffmpeg.sh
A follow up to #271.
In HW transcoding, demuxer is opened once and used, so it is necessary to check whether the input pixel format does not change in the middle. If a change is detected, free the input_ctx and reopen the demuxer again.
test 
```
go test -run TestTranscoder_DiscontinuityPixelFormat ./ffmpeg
go test --tags=nvidia -run TestNvidia_DiscontinuityPixelFormat ./ffmpeg
```
> fix middle pixel format changing issue

- ffmpeg/sign_cuda_test.go
- ffmpeg/sign_nvidia_test.go
#294 Create missing unit test for `signature_cuda` filter.
Sample video file `test.ts` is transcoded to 720p and 360p profiles both using software encoder and nvidia encoder, 4 output files in total.
We make sure output files are created.
`CompareSignatureByPath()` function is used to compare cuda output to cpu output, meaning that the signatures fuzzy match.
- `cd lpms/ffmpeg`
- `go test -v --tags=nvidia -run TestNvidia_SignDataCreate`
- expect in output:
```
=== RUN   TestNvidia_SignDataCreate
--- PASS: TestNvidia_SignDataCreate(7.25s)
PASS
ok      github.com/livepeer/lpms/ffmpeg 7.487s
```
- Check `nvtop` to see hardware encoding was used:
> Unit test for signature_cuda filter

- ffmpeg/api_test.go
- ffmpeg/extras.c
- ffmpeg/extras.h
- ffmpeg/ffmpeg.go
- ffmpeg/nvidia_test.go
- **For two segments, read stream data directly from the memory buffer at same time.**[#292](https://github.com/livepeer/internal-project-tracking/issues/292)
We have defined two following functions in C level which are callable from outsite. 
`int lpms_compare_video_bybuffer(void *buffer1, int len1, void *buffer2, int len2)`[here](https://github.com/livepeer/lpms/pull/292/files#diff-998114575433dc60658ff6542df0970e08cef7970396134aeedf868b90aace10R343)
`int lpms_compare_video_bypath(char *vpath1, char *vpath2)`[here](https://github.com/livepeer/lpms/pull/292/files#diff-998114575433dc60658ff6542df0970e08cef7970396134aeedf868b90aace10R367)
In the second function, the file paths of two different video segments will be used as input values, while the buffers and the buffer sizes will be used …
> add functions for video comparison

- .circleci/config.yml
This is related with #301 
- Before we run `TestTranscoder_DetectionFreq` function, we need to download `tasmodel.pb` first.
- We need to set the library path for the Tensorflow linking in env variables.
- To build the ffmpeg with libtensorflow, `experimental` should be contained in BUILD_TAGS.
> Fix the failure of TestTranscoder_DetectionFreq in CircleCI

- segmenter/video_segmenter_test.go
This was causing tests to fail when I ran locally (M1 Mac) due to the flag being used wrongly for that version of Netcat:
https://github.com/st3fan/osx-10.9/blob/master/netcat-20/netcat.c#L271-L276
It also seems to not be a valid flag for some Linux versions:  https://linux.die.net/man/1/nc
> segmenter: Remove invalid netcat flag in test

- doc/trim_output_tracks.md
- ffmpeg/encoder.c
- ffmpeg/ffmpeg_test.go
Removed failing checks.
Didn't found good way to replace temporary failing checks.
Used manual test to verify proper operation:
- got input file timestamps: [frames_input.csv](https://github.com/livepeer/lpms/files/8397619/frames_input.csv)
- got encoded file timestamps: [frames_output.csv](https://github.com/livepeer/lpms/files/8397620/frames_output.csv)
- Produced video track contains proper frames
- Verified frames visually
Hard to implement above checks in code without additional image transformations. @oscar-davids any methods available we can use to verify correct set of frames are in output?
When using tensorflow and flushing output in `process_out()` function `getmetadatainf()` call causes error to propagate and `TestTranscoder_DetectionFreq` test fails.
Added …
> Fix clip tests

- .circleci/config.yml
- segmenter/video_segmenter_test.go
Related to [git Action CI](https://github.com/livepeer/livepeer-infra/issues/803)
When have a test on the host, we get "Connection refused" error message but get "Cannot assign requested address" error message in a container on K8s.
I try to find a solution with helm chart on K8s, but can't find a reasonable way to fix this. so decided to add another error message to the Unit test code.
Thank @cyberj0g  for fixing CI/CD error on ubuntu.
> Add error message for K8s container

- .github/runner/Dockerfile
- .github/workflows/linux.yml
- test.sh
We can switch from CircleCI to GH actions for CI and enable GPU tests.[#284]
The pre-requisites to enable GPU tests on GitHub actions would be like followings.
1. Install NVIDIA driver and Cuda toolkit on the host VM.
2. Install docker and nvidia-docker
3. Run [nvidia-patch](https://github.com/keylase/nvidia-patch)
>In some cases, there is a restriction on maximum number of simultaneous NVENC video encoding sessions imposed by Nvidia to consumer-grade GPUs. To remove this restriction, I am using [NVENC patch](https://github.com/keylase/nvidia-patch).
4. Build docker image and run docker container
>Run the following command to run docker container
`nvidia-docker run -it --runtime=nvidia --gpus all --network host -e ORGANIZATION=livepeer -e REPOSITORY=lpms -e ACCESS_TOKEN=XXXXXXXXXX …
> Add github actions for lpms

- ffmpeg/ffmpeg.go
The problem here was to ensue that C memory would not leak. Old code relied on Go's defer statements, but new code was no longer limited to single function scope. At first I though I may do checks first, allocation second but the problem remained because some of the outputs may get configured correctly (and C memory allocated) and then subsequent one may fail, triggering memory leaks. It could be done in two passes, first checks for all the outputs, then allocations but then some allocations share conditional logic with checks, so a lot of extra code.
I finally decided on the current approach - configuration creation function _always_ returns outputs array, and destroy function should _always_ be called. Then destroy function is releasing only the memory that actually was allocated. I am …
> C configuration build changes

- ffmpeg/extras.c
For #[352](https://github.com/livepeer/internal-project-tracking/issues/352)
Regarding [this ](https://github.com/livepeer/lpms/pull/279#discussion_r778763259)changes, there are differences in GPU/CPU in bitrate, timestamp, and packet count. so, it removed the comparison of these.
> remove metadata comparison in the video comparison

- ffmpeg/api_test.go
- ffmpeg/ffmpeg.go
- ffmpeg/nvidia_test.go
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
For fixing #337 
- added lastacodec variable in Transcoder structure
- call ["open_input"](https://github.com/livepeer/lpms/blob/622b50738904a1c7d75a3b9650f1cf1341980670/ffmpeg/decoder.c#L298) to recognize the audio track
- added unit test [here](https://github.com/livepeer/lpms/blob/e7ca14c09ef1e1302963b844376acd0dd8b1bc00/ffmpeg/api_test.go#L1575)
> reopen context when it added audio track into the segment

- ffmpeg/ffmpeg.go
- ffmpeg/transcoder.c
- ffmpeg/transcoder.h
Due to my omission the previous solution was going against the
grain of upcoming refactoring changes in lpms_transcode().
Basically the idea is to have streamlined transcoder init() code
so that changes such as Low Latency can be implemented easily in
one place, instead of being distributed in many flows.
Besides, adding yet another "mode" to lpms_transcode() is not
really needed. The transcoder is kinda like any other object
instance - it retains its status between the lpms_transcode()
calls. So I think it is easier to add extra operations (such
as lpms_transcode_close_demux() introduced here) to change said
state, instead of increase the complexity of lpms_transcode()
call.
And finally, perhaps most important thing:
Changes like these are needed because LPMS doesn't really chave
good …
> Demux reopen not in lpms_transcode()

- ffmpeg/encoder.c
- ffmpeg/filter.h
For [#379](https://github.com/livepeer/internal-project-tracking/issues/397)
After a long time of transcoding on GPU, exactly 6.5 hours, sometimes [here](https://github.com/livepeer/lpms/blob/8bb5759971e725e04a5636e790737dd7adb930a6/ffmpeg/encoder.c#L382), got weird packets which[ DTS > PTS](https://github.com/livepeer/FFmpeg/blob/dd7e5c34e75fcb8ed79e0798d190d523e11ce60b/libavformat/mux.c#L604). But muxer doesn't agree with those packets. so we make DTS and PTS of these packets accept in muxer.
> add exception proc for weird DTS and PTS

- ffmpeg/decoder.h
- ffmpeg/encoder.c
- ffmpeg/extras.c
- Hardware transcoding fails when livepeer is sent segments with very few video frames. It works fine when running software trascoding but fails in hardware trascoding. This is caused because internal buffers of Nvidia's decoder are bigger compared to software decoder, current to solve this issue we defined [SENTINEL_MAX ](https://github.com/livepeer/lpms/blob/fb9f13d91fc2b20e51b799216c322dbfc30f07c5/ffmpeg/decoder.h#L33)= 5, but still appears issue on other GPU(i.e. 1660).
So changed  SENTINEL_MAX to 8.
- Rarely, the first audio packet is dropped during transcoding. Therefore, do not compare the first audio packets those timestamp equals 0 [here](https://github.com/livepeer/lpms/blob/fb9f13d91fc2b20e51b799216c322dbfc30f07c5/ffmpeg/extras.c#L344).
> change video comparison function

- ffmpeg/extras.c
Occasionally, B receives different renditions that are mismatched in audio data from Ts , At this time we can see that one or two packets are missed compared to the original audio data.
I tried to explain the cause in the video transcoding pipeline, but it could not be reproduced in the local environment, appeared occasionally in the staging environment, and no weird parts were found in the source code.
So to increase accuracy in the audio mismatch problem, chi-distance based on binary data histogram was introduced, and the source was modified to determine that the audio data were the same when the data are almost similar.
> calculate similarity per audio packet

- ffmpeg/ffmpeg.go
This fix unmasks real error we are seeing on production.
Instead of `profile 360x640 size out of bounds 146x146-4096x4096 input=0x0 adjusted 360x-9223372036854775808 or -9223372036854775808x640` error message we will receive `TranscoderInvalidVideo`
> Skip resolution adjustment in case of missing video track

- ffmpeg/videoprofile.go
- segmenter/video_segmenter.go
Essentially a no-op for this project, but it's a good practice to have `import "C"` in files that use CGO. This means that other things can be compiled with `CGO_ENABLED=0` and it won't necessarily break.
> ffmpeg: add 'import C' where it's used

- ffmpeg/ffmpeg.go
- ffmpeg/videoprofile.go
Since we set CQ based on the `quality`, then to avoid confusion, let's not use the `crf` name.
Discussed more in [Discord](https://discord.com/channels/423160867534929930/1140578841136484402/1149583985530380380).
> Rename profile.CRF to profile.Quality

- ffmpeg/ffmpeg.go
Windows binaries with CUDA SDK are not working. It's probably fixable, but I think it would require at least 1 week of work. I guess it's not worth spending time on that, so for Windows AMD64 GPU, let's use the old `scale_cuda`. That means that we'll use `scale_npp` only in Linux.
> Use scale_cuda in Windows

- ffmpeg/api_test.go
- ffmpeg/encoder.c
- ffmpeg/ffmpeg_test.go
- ffmpeg/filter.c
- ffmpeg/filter.h
Manually calculate the duration of each frame and set
the PTS to that before submitting to the filtergraph.
This allows us to better support variable frame rates,
and is also better aligned with how ffmpeg does it.
This may change the number of frames output by the FPS
filter by +/- 1 frame. These aren't issues in themselves
but breaks a lot of test cases which will need to be updated.
Previously we were depending on a calculated frame rate ([r_frame_rate](https://github.com/FFmpeg/FFmpeg/blob/dd5f665b4010f8a0142ce3cba3305b173eb37dfe/libavformat/avformat.h#L903-L911))
but this isn't set to a sensible value for VFR streams. Packet duration also
can't be relied on (see the new VFR test case where each duration is N/A),
so we need to do some manual bookkeeping to calculate the timestamp …
> Improve VFR support

- cmd/example/main.go
- cmd/example/simple/simple.go
- core/lpms.go
- vidlistener/listener.go
- vidlistener/listener_test.go
This is to allow us to signal different types of errors in go-livepeer and ultimately pass back different HTTP statuses from the Broadcaster depending on the stream creation failure reason
> Add an error return to makeStreamID to make issues explicit

- ffmpeg/nvidia_test.go
The nvidia test suite was never run after #393 so this breakage was not noticed.
> Update nvidia tests to pass with VFR changes.

- .github/workflows/build.yaml
- ffmpeg/api_test.go
- ffmpeg/decoder.c
- ffmpeg/encoder.c
- ffmpeg/extras.c
- ffmpeg/ffmpeg_test.go
- ffmpeg/filter.c
- ffmpeg/filter.h
- ffmpeg/nvidia_test.go
- ffmpeg/transcoder.c
- ffmpeg/transmuxer_test.go
- install_ffmpeg.sh
- segmenter/video_segmenter_test.go
Updates to the latest ffmpeg release (7.0.1) and adjust unit tests to match some slightly changed behaviors in the CLI that is used for testing. This also uncovered a bug that was fixed as described in #405 but is also included in this PR (see [commit message](https://github.com/livepeer/lpms/commit/99946629fc53df81fc1c7e1fd473a4d70811b861)).
The unit tests all pass with zero timestamp adjustments, so this update should be reasonably backwards-compatible with older LPMS. In fact, the [updated LPMS transcoder](https://github.com/livepeer/lpms/commit/73d216a479c72ed8e35dc8afea3f7ce2e242831e) still passes the full test suite even when the test suite is running the old ffmpeg CLI. The [unit test changes](https://github.com/livepeer/lpms/commit/64889eb82347a38ed630b724afe5dab9205e79d5) are …
> Update FFmpeg to 7.0.1

- README.md
This pull request ensures that developers are aware of the extra build flags they have to run when installing ffmpeg for the tests to be successful. It also cleans up the README a bit.
> docs: update README with extra dev info

- README.md
This pull request ensures that people are aware that they need to add the compiled vrsion of ffmpeg to the PATH to be able to run the tests.
> docs: improve test instructions

- ffmpeg/encoder.c
- ffmpeg/ffmpeg_test.go
This mostly ensures that non-B frames have the same dts/pts.
The PTS/DTS from the encoder can be "squashed" a bit during rescaling back to the source timebase if it is used directly, due to the lower resolution of the encoder timebase. We avoid this problem with the PTS in in FPS passthrough mode by reusing the source pts, but only rescale the encoder-provided DTS back to the source timebase for some semblance of timestamp consistency. Because the DTS values are squashed, they can differ from the PTS even with non-B frames.
The DTS values are still monotonic, so the exact numbers are not really important. However, some tools use `dts == pts` as a heuristic to check for B-frames ... so help them out to avoid spurious B-frame detections.
To fix the DTS/PTS mismatch, take the difference …
> ffmpeg: Rescale DTS better during FPS passthrough

- ffmpeg/decoder.c
- ffmpeg/decoder.h
- ffmpeg/encoder.c
- ffmpeg/encoder.h
- ffmpeg/ffmpeg_test.go
- ffmpeg/filter.c
- ffmpeg/nvidia_test.go
- ffmpeg/transcoder.c
Also adds a bunch of other changes necessary to better support
mid-stream resolution changes.
Unfortunately with CUVID there still seems to be a brief flash of
green (looks to be the length of the decoder's internal frame buffer)
but we can tackle that separately. This PR simply makes the transcoder
1) not crash, and
2) correctly encode mid-stream rotations, including with CPUs
Depends on https://github.com/livepeer/lpms/pull/417
The following commits can all stand alone except the last one (unit tests) depends on all of them. I can make separate PRs if that is preferable for ease of review. Let's also keep these commits separate when merging.
[ffmpeg: Flush filters before re-initialization.](https://github.com/livepeer/lpms/commit/dd12875e9b5ce2114b6aa1be2ae1a35f764cb296) 
Also add …
> Fix CUVID crash on resolution change

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/nvidia_test.go
This allows the transcoded resolution to be re-clamped correctly if the input resolution changes mid-segment.
As a result, we no longer need to do this clamping in golang.
Additionally, make the behavior between GPU and CPU more consistent by applying nvidia codec limits and clamping CPU transcodes.
Note that we effectively do not use the smaller side of the requested resolution. Eg, the "720" would be ignored in "1280x270"
Open question - should we error out if the requested VideoProfile resolution is under/over the codec limits, rather than implicitly clamping the resolution within the limits? Previously we were erroring out if the W/H was `<= 0` but I am not sure why we would not also error out on , say, 1x99999
> ffmpeg: Clamp resolutions in filter expression

- ffmpeg/ffmpeg.go
Updated the FFmpeg preset from slow to medium because the increased computation time required for slow does not provide a significant visual quality improvement. This change optimizes the balance between performance and quality.
> Update ffmpeg.go  change preset from slow to medium

- ffmpeg/decoder.c
- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
- ffmpeg/transcoder.c
This adds demuxer options as a complement to the existing [encoder/muxer](https://github.com/livepeer/lpms/blob/ffde2327537517b3345162e9544704571bc58a34/ffmpeg/ffmpeg.go#L112-L114) options which allows us to
1. explicitly select the demuxer to use if probing doesn't return a good result, and
2. configure the demuxer with additional options
This has come up a few times while looking at various things so it is good to have an API that is fully configurable out of the box.
This was partially implemented in #420 but this is more complete - it actually allows for demuxer selection and adds test cases.
> ffmpeg: Add demuxer options.

- install_ffmpeg.sh
This should make RTMP output work on production (non-debug) builds of LPMS
> install_ffmpeg: Add FLV muxer

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
Regression from https://github.com/livepeer/lpms/pull/426, luckily caught by go-livepeer tests
> Fix crash on PNG options

- README.md
This pull request updates the Discord invite URL from a temporary (expiring) link to a fixed (permanent) one to ensure long-term accessibility.
>  docs: replace temporary Discord invite URL with permanent URL

- install_ffmpeg.sh
We've been hit more than once because those domains were down or SSL error or something else.
> Replace videolan.org and nasm.us dependecies from `install_ffmpeg.sh`

- ffmpeg/ffmpeg.go
- ffmpeg/ffmpeg_test.go
Fix to test input segments for durations longer than 5 minutes. 
Fixes bug that created ridiculously large output segments.
[long-ts.log](https://github.com/user-attachments/files/20470410/long-ts.log)
[wrong-ts.log](https://github.com/user-attachments/files/20470411/wrong-ts.log)
cc @rickstaa
> add duration check for input files
