livepeer/lpms

README.md
bin/srs.conf
cmd/lpms.go
lpms.go
stream/fileStream.go
stream/stream.go
stream/stream_test.go
transcoder/external.go
transcoder/external_test.go
vidlistener/listener.go
vidlistener/listener_test.go
vidplayer/player_test.go

Adding "FileStream" so a video stream can be written to disk.  This was used to test for SRS transcoding consistency.  The result looks good so far.

Add file stream

---

vidplayer/player.go
vidplayer/player_test.go

Attempt to minimize HLS delay.  For me it's about 10s now.

only keep the last 2 segments for hls

---

lpms.go
stream/stream.go
vidlistener/listener.go
vidlistener/listener_test.go

Add the video format when creating the video stream - need this info for the app (also will be useful for the node)

desktop app integration

---

cmd/rtmp_segment_packer/main.go
cmd/runner/main.go
lpms.go
segmenter/video_segmenter.go
segmenter/video_segmenter_test.go
stream/file_stream.go
stream/hls.go
stream/queue.go
stream/stream.go
stream/stream_subscriber.go
stream/stream_subscriber_test.go
stream/stream_test.go
transcoder/external_test.go
vidlistener/listener.go
vidlistener/listener_test.go
vidplayer/player.go
vidplayer/player_test.go

segment length of 2 was causing a lot of buffering.  Increasing to 5.

add ffmpegPath, bugfixes

---

core/videoprofile.go

Added in a missing video profile in the look up map

Added missing video profile in lookup map

---

cmd/example/main.go
ffmpeg/ffmpeg.go
ffmpeg/lpms_ffmpeg.c
ffmpeg/lpms_ffmpeg.h
ffmpeg/videoprofile.go
transcoder/ffmpeg_segment_transcoder.go
transcoder/ffmpeg_segment_transcoder_test.go

Commits roughly broken down by feature for easier review.

Transcoding via FFmpeg API

---

cmd/example/main.go
ffmpeg/ffmpeg.go
transcoder/ffmpeg_segment_transcoder.go
transcoder/interface.go

Should have added internal LPMS tests for these cases as well, but getting this PR out for the sake of expediency so we can merge this into the goclient.

Fix breakage exposed by goclient.

---

circle.yml
cmd/example/main.go
ffmpeg/ffmpeg.go
ffmpeg/lpms_ffmpeg.c

Miscellaneous fixes.

---

ffmpeg/ffmpeg.go
ffmpeg/lpms_ffmpeg.c
install_ffmpeg.sh

ffmpeg: Remove deprecated functions.
---
ffmpeg: Complete library listing for cgo linking.
Makes compiling with shared libaries easier (it is much faster).
---
install_ffmpeg: Synchronize with goclient.

Misc ffmpeg changes

---

cmd/example/main.go
cmd/rtmp_segment_packer/main.go
cmd/rtmp_segment_packer/main_test.go
core/lpms.go
segmenter/video_segmenter.go
vidlistener/listener.go
vidplayer/player.go

Additional control to start RTMP or HTTP (for example, no reason for bootnode to run RTMP server).

Small Cleanup

---

vidlistener/listener.go
vidplayer/player.go

When we don't want to start the RTMP server.

Fix a crash

---

circle.yml
cmd/example/main.go
core/lpms.go
install_ffmpeg.sh

The defaults listen to all interfaces, so we need to pass in localhost explicitly from goclient.

Use a LPMS config struct, add RTMP/HTTP binding IPs.

---

ffmpeg/ffmpeg.go
ffmpeg/lpms_ffmpeg.c
ffmpeg/lpms_ffmpeg.h
segmenter/video_segmenter.go
segmenter/video_segmenter_test.go

Needed to support https://github.com/livepeer/go-livepeer/issues/316

segmenter: Add StartSeq option.

---

core/lpms.go
ffmpeg/ffmpeg.go
ffmpeg/ffmpeg_test.go
ffmpeg/lpms_ffmpeg.c
segmenter/video_segmenter_test.go
transcoder/ffmpeg_segment_transcoder_test.go
vidplayer/player.go

Support non-default HTTP muxers.

---

circle.yml
install_ffmpeg.sh
vidlistener/listener.go
vidlistener/listener_test.go

Right now, if `makeStreamID` returns empty string, connection just left hanging, so any any client (FFmpeg, OBS) just hangs trying to send data and not getting any response.

Close connection if stream id was not created

---

ffmpeg/ffmpeg_test.go
ffmpeg/lpms_ffmpeg.c

Fixes some video skipping during playback
Fixes https://github.com/livepeer/lpms/issues/112
Maybe fixes https://github.com/livepeer/go-livepeer/issues/803

ffmpeg: Properly flush filters / encoders after EOF.

---

cmd/example/main.go
core/lpms.go
ffmpeg/videoprofile.go
segmenter/video_segmenter.go
segmenter/video_segmenter_test.go
stream/basic_hls_video_manifest.go
stream/basic_hls_video_test.go
stream/basic_hls_videostream.go
stream/hls.go
stream/interface.go
stream/stream.go
vidplayer/player.go
vidplayer/player_test.go

Change links from 	`github.com/ericxtang/m3u8`
to `github.com/livepeer/m3u8`

`m3u8` lib moved to Livepeer Github account

---

cmd/example/simple/simple.go

Fixes compilation.
Closes #137

simple: Update to new AppData API.

---

go.mod
go.sum

update github.com/livepeer/m3u8 dependency to v0.11.0

move to github.com/livepeer/m3u8 v0.11.0

---

cmd/transcoding/transcoding.go
ffmpeg/ffmpeg.go
ffmpeg/ffmpeg_test.go
ffmpeg/lpms_ffmpeg.c
ffmpeg/lpms_ffmpeg.h
ffmpeg/videoprofile.go

Return count of encoded pixels from transcoder.

---

ffmpeg/lpms_ffmpeg.c

correctly free cloned packet

---

ffmpeg/lpms_ffmpeg.c

Check if buffer was actually allocated
In case `avformat_open_input` failed, close input that was
opened by `avio_open`
(`avformat_open_input` will not automatically close input
if it was provided to it)

Close input in case of error

---

ffmpeg/lpms_ffmpeg.c

The in-out structs are allocated but not freed if the function exits
early, such as if decoding is not required.
Make any early exits jump to the cleanup routine to avoid these errors
in the future. Also move the allocations so they don't occur if an early
exit is needed.
Make the audio filter more symmetrical with respect to video.

ffmpeg: Plug memory leak in filtergraph init.

---

ffmpeg/ffmpeg_test.go
ffmpeg/lpms_ffmpeg.c

Makes things work better with random VOD samples that may
contain data or subtitle streams.

ffmpeg: Ignore unknown streams in transcoder.

---

go.mod
go.sum

Update m3u8 library to v0.11.1 which has a race-condition fix around the `Count()` method.

mod: Update m3u8 to v0.11.1

---

ffmpeg/ffmpeg.go

Temporary PR till we figure out what's wrong with multiple GPU support.

ffmpeg: Hardcode scene classification on GPU 0

---

README.md
doc/contributing.md

Add contribution guide which can document guidelines for contributing to LPMS and also tips for contributing (i.e. a debugging guide for working with Go + C + cgo + ffmpeg).

Add contribution guide

---

doc/contributing.md
ffmpeg/ffmpeg.go
ffmpeg/transcoder.c
ffmpeg/transcoder.h
install_ffmpeg.sh

[Issue 1997](https://github.com/livepeer/go-livepeer/issues/1997)

Pass device id parameter

---

ffmpeg/decoder.c
ffmpeg/ffmpeg.go
ffmpeg/ffmpeg_errors.go
ffmpeg/transcoder.c
ffmpeg/transcoder.h

For details: https://github.com/livepeer/go-livepeer/issues/1921
Stack trace for illegal address error: https://github.com/livepeer/lpms/issues/239

ffmpeg: Panic on illegal address errors

---

ffmpeg/extras.c
ffmpeg/extras.h
ffmpeg/ffmpeg.go
ffmpeg/ffmpeg_test.go
ffmpeg/videoprofile.go
stream/stream.go

LPMS part of https://github.com/livepeer/go-livepeer/pull/2191

Add function to get codec info

---

ffmpeg/videoprofile.go

Another small part of https://github.com/livepeer/go-livepeer/issues/2123
Should be merged before go-livepeer PR, because it has codec name to enum conversion function.

Support encoder parameter in transoding options JSON

---

ffmpeg/sign_test.go

unit test for CompareSignatureByBuffer with incomplete data

unit test for CompareSignatureByBuffer with incomplete data

---

ffmpeg/encoder.c
ffmpeg/ffmpeg.go
ffmpeg/filter.h
ffmpeg/transcoder.c

we need to clip audio stream too

also clip audio stream

---

ffmpeg/ffmpeg.go

Disable B frames in constrained high mode for Netint

---

ffmpeg/ffmpeg.go
ffmpeg/ffmpeg_darwin.go
ffmpeg/nvidia_test.go

Issue: https://github.com/livepeer/go-livepeer/issues/2364

Support for suppressing excessive logging on capabilities testing

---

doc/quirks.md

Documentation task: https://github.com/livepeer/lpms/issues/342
@oscar-davids please check if I missed something

Add paragraph on segments without audio to quirks.md

---

README.md

Issue: https://github.com/livepeer/lpms/issues/359

Add Readme section on running failed transcodes test

---

ffmpeg/ffmpeg.go
ffmpeg/nvidia_test.go

Related go-livepeer PR: https://github.com/livepeer/go-livepeer/pull/2851

Change scale_cuda to scale_npp

---

vidplayer/player.go

Fixed typo from 'writting' to 'writing'

Fixed typo
